### ISSUE TITLE
Input fields expose variable names.

### ISSUE THREAD

**Issue by Rufinito** [sunmockyang/date-calculator#11]
http://calculatedates.com/ shows $$INPUT1$$ and $$INPUT2$$ in the fields.

![issue](https://cloud.githubusercontent.com/assets/3335157/19199776/ba362e38-8c93-11e6-901f-bee455ee9d9f.PNG)

**Comment by sunmockyang** [comment]
Fixed in https://github.com/sunmockyang/date-calculator/commit/5dc8d6720134d27f8c0576204468c7d770e915fa
