### ISSUE TITLE
Does it work without JavaScript?

### ISSUE THREAD

**Issue by aarongustafson** [sunmockyang/date-calculator#7]

**Comment by sunmockyang** [comment]
Hi, the latest master branch should display a message saying `Sorry, Date Calculator requires JavaScript to be enabled to work.` if javascript has been disabled.

**Comment by aarongustafson** [comment]
Just an FYI: With progressive enhancement being a focal part of the contest, your project won’t fair well without a no-JS experience: https://a-k-apart.com/faq#pe

**Comment by sunmockyang** [comment]
Ok, thank you for letting us know.

**Comment by sunmockyang** [comment]
Added server side logic to handle cases where there is no client-side javascript
